### ISSUE TITLE
Feature request: Add support for Inertia.js

### ISSUE THREAD

**Issue by MichaelNZ85** [barryvdh/laravel-debugbar#1389] opened 2023-02-08 22:37 UTC
[Inertia.js](https://inertiajs.com/) allows you to serve frontend framework components (React/Vue/Svelte components) directly from the Laravel code. It's essentially the "glue" that can stick the frontend and backend together without the need for an API. 

However, Laravel + Inertia + React/Vue is not supported by the Laravel Debugbar. Since Inertia uses only one Blade template (which is essentially a master template), then the View tab in the Debugbar is pretty bare. It would be great if you could add support for Inertia, showing which component was rendered and which props were sent to said component.

**Comment by websolutionfalcon** [comment] 2023-02-09 06:27
+1 
It will be great to support Inertia

**Comment by TheKelvinPerez** [comment] 2023-03-22 17:30
Yes +1 as well this would be an amazing feature

**Comment by Dibbyo456** [comment] 2023-03-29 06:22
+1

**Comment by pilutiful** [comment] 2023-09-13 11:14
Yes please +1

**Comment by khalidmaquilang** [comment] 2023-10-11 19:53
any update on this?

**Comment by parallels999** [comment] 2023-10-11 20:03
Hi, feel free to make a PR for that

**Comment by erikn69** [comment] 2023-10-11 22:45
Try #1478 and let your review

**Comment by Dibbyo456** [comment] 2023-10-16 09:16
Thank you for the patch, I can confirm its working for Svelte. 👍

<img width="1308" alt="Screenshot 2023-10-16 at 2 44 39 PM" src="https://github.com/barryvdh/laravel-debugbar/assets/18257605/ef092568-5459-4548-975e-4b3115ac62e4">

**Comment by oozone** [comment] 2023-10-16 09:43
This is fantastic. Thank you all!

**Comment by erikn69** [comment] 2023-10-16 13:35
Please, any review on https://github.com/barryvdh/laravel-debugbar/pull/1479, that way there is a greater chance of it being merged.

**Comment by Dibbyo456** [comment] 2023-10-16 13:55
> Please, any review on #1478, that way there is a greater chance of it being merged.

That’s the PR I tested on Svelte. It works for me.

**Closed** 2024-01-30 14:24 UTC

**Comment by philharmonie** [comment] 2024-03-11 14:32
Unfortunately, it's not working with vue3.

**Comment by philharmonie** [comment] 2024-03-11 17:29
Yes it kinda works, but when I load e.g. 10 users `return inertia('Users/Index', ['users' => User::all()])` it shows 10 models in the debugbar for a second and then immediately it refreshes and doesn't show the query for the users table.

**Comment by parallels999** [comment] 2024-03-11 17:53
>then immediately it refreshes and doesn't show the query for the users table.

That is the ajax, it is the expected behaivor https://github.com/barryvdh/laravel-debugbar/issues/1490
![image](https://github.com/barryvdh/laravel-debugbar/assets/109294935/227e76d8-8d20-44a4-ab12-931343cc658e)
Check that selector, or disable it
https://github.com/barryvdh/laravel-debugbar/blob/67e43efa430a9627059963c7e1602c3f5458e873/config/debugbar.php#L126
