### ISSUE TITLE
Debugbar crashing in applications with Inertia installed on requests that do not use Inertia

### ISSUE THREAD

**Issue by alex-osborn** [barryvdh/laravel-debugbar#1523] opened 2024-02-13 22:35 UTC
Laravel Version: v10.44.0
Debugbar Version: v3.10.2

The recent merge to add InertiaJs support is buggy and can cause the application to crash.

We're getting crashes with the error  `Undefined array key \"component\"` at `vendor/barryvdh/laravel-debugbar/src/DataCollector/ViewCollector.php:73` on many pages after upgrading.

https://github.com/barryvdh/laravel-debugbar/pull/1478

`src/DataCollector/ViewCollector.php::addView()` detects Inertia by checking if the `Inertia` class exists and the view data has a `page` key set, and then assumes that a `component` key will exist.

```
        if (class_exists('\Inertia\Inertia') && isset($data['page'])) {
            $data = $data['page'];
            $name = $data['component'];

            if (!@file_exists($path = resource_path('js/Pages/' . $name . '.js'))) {
                if (!@file_exists($path = resource_path('js/Pages/' . $name . '.vue'))) {
                    if (!@file_exists($path = resource_path('js/Pages/' . $name . '.svelte'))) {
                        $path = $view->getPath();
                    }
                }
            } else {
                $type = 'react';
            }
        }
```
This needs additional checks - having Inertia loaded and having a key called `page` but **not** using Inertia for the request is a valid and common case. For example, auth/login pages or any other request in the app not using Inertia. 

As an aside, the implementation includes hard-coded assumptions around the Inertia directory structure which aren't always true - see `$path = resource_path('js/Pages/' . $name . '.js'` etc (for example our paths don't match this structure), but this shouldn't be a major issue as it would just mean the path isn't detected correctly.

**Comment by erikn69** [comment] 2024-02-13 22:40
- try https://github.com/barryvdh/laravel-debugbar/pull/1516

**Comment by wizzymore** [comment] 2024-02-14 02:00
I get an issue with debugbar since the last composer update as well.
`Upgrading barryvdh/laravel-debugbar (v3.9.2 => v3.10.2)`

```
Trying to access array offset on int
```
![image](https://github.com/barryvdh/laravel-debugbar/assets/25827787/ad973aff-0575-4534-afe9-8063be4438eb)

We use inertia only in some new parts of the app, this one doesn't use Inertia.
The funny this is that if i remove the sole livewire component on the page ( handling polling notifications ) the page works without a problem.
Setting 'livewire' => false in the config doesn't fix the issue tho, it is fixed only by removing the component and by removing the 'views' collector, so there is something wrong with the collector.

**Comment by alex-osborn** [comment] 2024-02-14 02:36
> * try [Add test to check if $data['component'] exist #1516](https://github.com/barryvdh/laravel-debugbar/pull/1516)
> 
> Also, I don't use Inertia, could you make a PR to improve that functionality?

I've had a closer look at this - I realised I misunderstood the `component` check at first glance. It's not checking for a separate `component` key, it's assuming that if there is a key `page`, it is an array and it also has a child key `page.component`. This is then used to look up files on the filesystem.

I don't think this is easily fixable, I think the PR should be reverted. This isn't a safe way to identify Inertia requests. Passing a  `page` key to your view isn't reserved for Inertia, this is adding a major and unexpected restriction to the package.

I've had a look through the Inertia code and this seems like a tricky problem - I don't think there is an easy way to detect that a View object is actually for an Inertia request just from that object. This would require reaching into other parts of the app and again, this isn't straightforward - it isn't something Inertia easily exposes and there is a lot of configuration available to the user.

**Comment by erikn69** [comment] 2024-02-14 02:38
- Try #1525

**Comment by barryvdh** [comment] 2024-02-14 06:52
Is this already fixed with #1516 ?

**Comment by barryvdh** [comment] 2024-02-14 06:54
Can you try v3.10.3?

**Comment by wizzymore** [comment] 2024-02-14 11:05
Hi, i can confirm that for me it fixed the issue.

**Closed** 2024-02-14 11:10 UTC

**Comment by erikn69** [comment] 2024-02-14 11:39
v3.10.3 just remove Inertia feature

**Comment by wizzymore** [comment] 2024-02-14 19:51
> > * try [Add test to check if $data['component'] exist #1516](https://github.com/barryvdh/laravel-debugbar/pull/1516)
> > 
> > Also, I don't use Inertia, could you make a PR to improve that functionality?
> 
> I've had a closer look at this - I realised I misunderstood the `component` check at first glance. It's not checking for a separate `component` key, it's assuming that if there is a key `page`, it is an array and it also has a child key `page.component`. This is then used to look up files on the filesystem.
> 
> I don't think this is easily fixable, I think the PR should be reverted. This isn't a safe way to identify Inertia requests. Passing a `page` key to your view isn't reserved for Inertia, this is adding a major and unexpected restriction to the package.
> 
> I've had a look through the Inertia code and this seems like a tricky problem - I don't think there is an easy way to detect that a View object is actually for an Inertia request just from that object. This would require reaching into other parts of the app and again, this isn't straightforward - it isn't something Inertia easily exposes and there is a lot of configuration available to the user.

There is an easy fix for this, you get all of the middlewares registered in the application and check which extends `Inertia\Middleware` that one will contain the name of the layout rendered by inertia. This is an Inertia default and present in all Inertia applications.

**Comment by erikn69** [comment] 2024-02-14 20:45
- Try https://github.com/barryvdh/laravel-debugbar/pull/1527
