### ISSUE TITLE
Laravel 5.2 BadMethodCallException in Macroable.php line 81: Method before does not exist.

### ISSUE THREAD

**Issue by masterpowers** [barryvdh/laravel-debugbar#430] opened 2015-12-21 10:16 UTC
If a Set debug True i get 
```
BadMethodCallException in Macroable.php line 81:
Method before does not exist.
in Macroable.php line 81
at Router->__call('before', array(object(Closure))) in LaravelDebugbar.php line 152
at LaravelDebugbar->boot() in ServiceProvider.php line 108
at ServiceProvider->boot()
at call_user_func_array(array(object(ServiceProvider), 'boot'), array()) in Container.php line 507
at Container->call(array(object(ServiceProvider), 'boot')) in Application.php line 734
at Application->bootProvider(object(ServiceProvider)) in Application.php line 717
at Application->Illuminate\Foundation\{closure}(object(ServiceProvider), '15')
at array_walk(array(object(EventServiceProvider), object(RoutingServiceProvider), object(AuthServiceProvider), object(CookieServiceProvider), object(DatabaseServiceProvider), object(EncryptionServiceProvider), object(FilesystemServiceProvider), object(FoundationServiceProvider), object(PaginationServiceProvider), object(SessionServiceProvider), object(ViewServiceProvider), object(AppServiceProvider), object(AuthServiceProvider), object(EventServiceProvider), object(RouteServiceProvider), object(ServiceProvider)), object(Closure)) in Application.php line 718
at Application->boot() in BootProviders.php line 17
at BootProviders->bootstrap(object(Application)) in Application.php line 203
at Application->bootstrapWith(array('Illuminate\Foundation\Bootstrap\DetectEnvironment', 'Illuminate\Foundation\Bootstrap\LoadConfiguration', 'Illuminate\Foundation\Bootstrap\ConfigureLogging', 'Illuminate\Foundation\Bootstrap\HandleExceptions', 'Illuminate\Foundation\Bootstrap\RegisterFacades', 'Illuminate\Foundation\Bootstrap\RegisterProviders', 'Illuminate\Foundation\Bootstrap\BootProviders')) in Kernel.php line 232
at Kernel->bootstrap() in Kernel.php line 127
at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 99
at Kernel->handle(object(Request)) in index.php line 53
```
But if i set to false i get no error

Is this a Bug? How can i use this on Laravel 5.2?

**Comment by GrahamCampbell** [comment] 2015-12-21 10:17
Not a bug. See https://github.com/barryvdh/laravel-debugbar/pull/407.

**Comment by masterpowers** [comment] 2015-12-21 13:24
Any Quick Fix For This? 

Or Ill Just Wait for this Plugin to Be Updated by the Author...

**Comment by barryvdh** [comment] 2015-12-21 19:45
Should be fixed and tagged. Let me know if you still have problems.

**Closed by barryvdh** 2015-12-21 19:45 UTC

**Comment by renege** [comment] 2016-01-08 21:29
Still happening @barryvdh

**Comment by chisangu** [comment] 2016-02-09 11:48
Im having the same problem on a clean installation of Laravel 5

**Comment by jlien-calwater** [comment] 2016-02-24 17:05
Confirmed this is still and issue on 5.2.

**Comment by UnrulyNatives** [comment] 2016-02-27 00:50
I also have this error!

**Comment by devin0910** [comment] 2016-03-06 08:51
I also have this error, v5.2.20

**Comment by barryvdh** [comment] 2016-03-06 08:53
What version of debugbar are you on?

**Comment by devin0910** [comment] 2016-03-06 09:11
@barryvdh after i remove newrelic ext, the error is gone.  I find this solution and it works [https://pablumfication.co.uk/2015/12/23/laravel-5-2-new-relic-php-agent-issue/](https://pablumfication.co.uk/2015/12/23/laravel-5-2-new-relic-php-agent-issue/)

**Comment by devin0910** [comment] 2016-03-06 09:17
@barryvdh I commented on a wrong issue

**Comment by abhishek-gangwar** [comment] 2016-03-13 18:31
I am also facing the same issue

**Comment by Arkanius** [comment] 2016-05-10 21:35
Also getting this error on 5.2

**Comment by malhayek2014** [comment] 2016-07-07 22:16
+1 I get this error with Laravel 5.2.36 also when I try to cache relation like this

    public function pages()
    {

        return Cache::remember('pages_survey_id' . $this->survey_id , 180, function(){

           return $this->hasMany(SurveyPage::class, 'survey_id', 'survey_id')
                        ->orderBy('sort', 'asc')
                        ->orderBy('id', 'asc')
                        ->get();
        });

    }
