### ISSUE TITLE
Memory Exeption

### ISSUE THREAD

**Issue by DKarakis** [barryvdh/laravel-debugbar#750] opened 2017-11-27 15:39 UTC
I'm using ^3.1 version of debugbar on laravel 5.5. It was working flawlessly unless I hit one specific page. When I hit that page I'm having Allowed memory size of 134217728 bytes exhausted (tried to allocate 786432 bytes) error.

I've checked collectors one by one and found that db collector is crashing. I've relations on that page and it is currently loading up 144 data from relationship with 10 fields. It is failing while fetching data from relationship and tries to write to log path. I've already tried to change into redis. But it is failing also.

Have a good day.

**Comment by barryvdh** [comment] 2017-12-24 13:32
Closing as duplicate of #726

**Closed by barryvdh** 2017-12-24 13:32 UTC
