### ISSUE TITLE
Livewire 3 & SPA Mode: "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by devajmeireles** [barryvdh/laravel-debugbar#1567] opened 2024-03-11 14:20 UTC
I updated one of my projects to use Livewire 3 in SPA mode (wire:navigate) and after that, I noticed that DebugBar throws an error in the console log stating "Maximum call stack size exceeded".

![CleanShot 2024-03-11 at 11 16 09](https://github.com/barryvdh/laravel-debugbar/assets/60591772/c6b2e2b8-f110-444f-9603-6be500f48bb6)

... With this, the DebugBar stops to be rendered.

I confirmed that this error is related to Livewire 3's SPA mode because when I remove this, this error no longer appears.

**Comment by devajmeireles** [comment] 2024-03-11 14:21
It looks like the error is here:

![CleanShot 2024-03-11 at 11 21 21](https://github.com/barryvdh/laravel-debugbar/assets/60591772/d276ad96-d108-4b6d-a40e-b21435bf9055)

**Comment by barryvdh** [comment] 2024-03-11 14:28
@erikn69 because of https://github.com/maximebf/php-debugbar/pull/606 ?

**Comment by barryvdh** [comment] 2024-03-11 14:30
Hmm not really familiar with SPA mode, but probably because the parent is resolving to itself?

**Comment by barryvdh** [comment] 2024-03-11 14:32
Or maybe we can just check if the parent debugbar is not the same object as the current debugbar, to prevent a loop?

What is the easiest to replicate this? It seems turbolinks is deprecated for 2 years?

**Comment by erikn69** [comment] 2024-03-11 14:32
Maybe, 
```php
window.parent && window.parent != window.top && window.parent.phpdebugbar && window.parent.phpdebugbar != this
```

**Comment by erikn69** [comment] 2024-03-11 15:14
> the new version was able to fix the issue

new version not was a fix, was a regression, https://github.com/maximebf/php-debugbar/pull/613#issuecomment-1988590018 was a possible fix, but I was hoping you could corroborate it because I can't replicate your environment

**Comment by devajmeireles** [comment] 2024-03-11 15:22
> > the new version was able to fix the issue
> 
> new version not was a fix, was a regression, [maximebf/php-debugbar#613 (comment)](https://github.com/maximebf/php-debugbar/pull/613#issuecomment-1988590018) was a possible fix, but I was hoping you could corroborate it because I can't replicate your environment

What do you prefer? A demo repo or better instructions to test that piece of code?

**Comment by erikn69** [comment] 2024-03-11 15:48
In my first test I got the error, but after reloading browser cache(`CTRL + SHIFT + R`), the error disappeared, your error is because the old js is in the cache, try reloading that with `v1.20.0`

**Comment by erikn69** [comment] 2024-03-11 16:09
The fix https://github.com/maximebf/php-debugbar/pull/613#issuecomment-1988807700

**Closed** 2024-03-13 15:09 UTC
